# Generated by Django 4.1.7 on 2023-09-28 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.ImageField(default='D:/python/django/shivam/mysite/media/profile/400x300.png', upload_to='profile/'),
        ),
    ]
