# Generated by Django 4.1.7 on 2023-10-04 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_blogs_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='Art',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='blogs',
            name='Lifestyle',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='blogs',
            name='Nature',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='blogs',
            name='Technology',
            field=models.BooleanField(default=False),
        ),
    ]
