# Generated by Django 4.1.7 on 2023-10-04 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_blogs_art_blogs_lifestyle_blogs_nature_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogs',
            name='description',
        ),
    ]
